create table if not exists public.episodes_commodities (
  id uuid not null default gen_random_uuid(),
  episode_no bigint not null,
  episode_id text not null,
  ticker text not null,
  direction text not null,
  status text not null,
  state text,
  detected_window text,
  started_at timestamptz not null,
  ended_at timestamptz,
  end_reason text,
  peak_move_percent double precision,
  current_move_percent double precision,
  initial_move_percent double precision,
  reference_price double precision,
  trigger_price double precision,
  current_price double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reference_time timestamptz,
  exact_minutes integer,
  exact_label text,
  window_minutes integer,
  last_notification_at timestamptz,
  giveback_ratio double precision,
  giveback_pct double precision,
  asset_class text,
  latest_research_id uuid,
  last_alert jsonb,
  primary key (id)
);
