create table if not exists public.events_episodes (
  id uuid not null default gen_random_uuid(),
  episode_no bigint,
  episode_id text not null default ''::text,
  ticker text not null,
  event_type text not null,
  state text,
  direction text,
  detected_window text,
  detected_at timestamptz not null,
  move_percent double precision,
  price double precision,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  exact_minutes integer,
  reference_time timestamptz,
  reference_price double precision,
  notification_title text,
  notification_body text,
  notified_at timestamptz,
  should_notify boolean,
  giveback_pct double precision,
  measure jsonb,
  idempotency_key text,
  research_id uuid,
  short_reason text,
  asset_class text,
  primary key (id)
);
