create table if not exists public.market_session_bulletins (
  id uuid not null default gen_random_uuid(),
  market text not null,
  slot text not null,
  session_date date not null,
  timezone text not null,
  title text not null,
  body text not null,
  body_source text not null default 'perplexity'::text,
  yahoo_market_state text,
  probe_symbol text,
  open_price numeric,
  close_or_last_price numeric,
  day_change_percent numeric,
  previous_close numeric,
  quote_snapshot jsonb,
  perplexity_meta jsonb,
  push_sent_ok integer not null default 0,
  push_sent_failed integer not null default 0,
  recipient_count integer not null default 0,
  claimed_at timestamptz not null default now(),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (id)
);
